os: windows

language: bash

branches:
  only:
  - master
  
before_install:
  - git clone https://github.com/qt/qt5.git
  - cd qt5/
  - git checkout origin/5.14.1
  - git submodule update --init --recursive

before_cache:
cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    
env:
  global:
    - MAKEFLAGS="-j 2"
