os: windows

language: bash

branches:
  only:
  - master
  
before_install:
  - git clone https://github.com/qt/qt5.git

before_cache:
cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    
env:
  global:
    - MAKEFLAGS="-j 2"
