os: windows

language: bash

branches:
  only:
  - master
  
before_install:
before_cache:
  - git clone https://github.com/qt/qt5.git
  - cd qt5/
  - git checkout origin/5.14.1
  - git submodule update --init --recursive

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - $HOME/qt5winbuilder/qt5/
    
env:
  global:
    - MAKEFLAGS="-j 2"
