os: windows

language: bash

branches:
  only:
  - master
  
instal:
  
before_install:
  - git clone https://code.qt.io/qt/qt5.git
  - cd qt5/
  - git checkout origin/5.14.1
  - git submodule init
  - git submodule update
  - git submodule update --init --recursive
  
before_cache:

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - $HOME/qt5winbuilder/qt5/
    
env:
  global:
    - MAKEFLAGS="-j 2"
script:
