version: '{build}'

branches:
  only:
    - master
    
os: Visual Studio 2017

environment:
  matrix:
    - COMPILER: msys2
      PLATFORM: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      BIT: 64
      BUILDTOOL: autoconf
      
clone_script:
    - cmd:
      'git clone -q --branch=master https://github.com/ArtifeksNN/qt5winbuilder.git C:\projects\qt5winbuilder'
      'git checkout -qf %APPVEYOR_REPO_COMMIT%'
      'git submodule update --init --recursive'

install:
    - set
    - '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\install.bat'
  
build_script:
    - '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\build.bat'